[tool.poetry]
name = "backend"
version = "0.1.0"
description = ""
authors = ["sabrina1405 <sabrina.s.souzarosa@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
fastapi = "^0.142.1"
uvicorn = {extras = ["standard"], version = "^0.54.0"}
sqlalchemy = "^2.1.1"
psycopg = {extras = ["binary"], version = "^3.3.6"}
alembic = "^1.20.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
